---
galaxy_info:
  author: Jason DeTiberus
  description: OpenShift haproxy loadbalancer
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 7
dependencies:
- role: openshift_facts
- role: os_firewall
  os_firewall_allow:
  - service: haproxy stats
    port: "9000/tcp"
  - service: haproxy balance
    port: "{{ openshift_master_api_port | default(443) }}/tcp"
- role: os_firewall
  os_firewall_allow:
  - service: nuage mon
    port: "{{ nuage_mon_rest_server_port | default(9443) }}/tcp"
  when: openshift_use_nuage | default(false) | bool
- role: openshift_repos
